version: '3'
services:
  mysql5.7:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:3320:3306
    command: mysqld --innodb_use_native_aio=0

  mysql8.0:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:3321:3306
    command: mysqld --innodb_use_native_aio=0
